{"name": "test_mul_006", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <TestCases.file2_test.Test002 object at 0x00000288AA369850>\n\n    @pytest.mark.group3\n    def test_mul_006(self):\n        a = 2\n        b = 2\n        mul = a * b\n        print(\"Mul of a * b =\" + str(mul))\n        if mul == 5:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nTestCases\\file2_test.py:25: AssertionError"}, "start": 1722500044492, "stop": 1722500044493, "uuid": "9571dd20-2b36-41b5-bcab-6287096ba963", "historyId": "de97eb15b31777b13670bf87d278a414", "testCaseId": "de97eb15b31777b13670bf87d278a414", "fullName": "TestCases.file2_test.Test002#test_mul_006", "labels": [{"name": "tag", "value": "group3"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "file2_test"}, {"name": "subSuite", "value": "Test002"}, {"name": "host", "value": "DESKTOP-16HA8VL"}, {"name": "thread", "value": "12940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.file2_test"}]}